/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import controller.IOFile;
import controller.SoDTException;
import controller.TrongException;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.util.ArrayList;
import java.util.Comparator;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.KhachHang;
import model.SoTietKiem;
import model.NganHang;

/**
 *
 * @author Admin
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    private String fKH,fNH,fSo  ; 
    private List<NganHang> lNganHang  ;
    private List<KhachHang> lKhachHang ;
    private List<SoTietKiem> lSoTK ;
    private DefaultTableModel tmNH, tmKH, tmTK ; 
    private Boolean them, sua ;
    public Main() {
        initComponents();
        fKH = "src/controller/KH.DAT" ;
        fNH = "src/controller/NH.DAT" ;
        fSo = "src/controller/STK.DAT" ;
        String[] khachhang = {"Ma KH", "Ho va ten", "Dia chi", "Loai khach hang"} ;
        String[] nganhang = {"Ma NH", "Ten ngan hang", "Lai suat theo nam"} ;
        String[] so = {"Ma KH", "Ho va ten" , "Ma NH" , "Ten ngan hang" , "So tien gui", "So thang gui", "Ngay gui"} ;
        tmKH = new DefaultTableModel(khachhang,0) ;
        tmNH = new DefaultTableModel(nganhang, 0) ;
        tmTK = new DefaultTableModel(so, 0) ;
        KHtb.setModel(tmKH);
        NganHangtb.setModel(tmNH);
        jTable3.setModel(tmTK); 
        cappnhatKHbt.setEnabled(false);
        capnhatNHbt.setEnabled(false);
        them = false ;
        sua = false ;
        loadMa() ;
        loadKhachHang() ;
        loadNganHang() ; 
        loadSoTK() ;
    }
    
    public NganHang getSachByMa(int maS){
        for(NganHang x : lNganHang){
            if(x.getId() == maS){
                return x ;
            }
        }
        return null ;
    }
    
    public KhachHang getBanDocByMa(int maBD){
        for(KhachHang x : lKhachHang){
            if(x.getId() == maBD){
                return x ;
            }
        }
        return null ;
    }
        
    public void loadMa(){
        MaKHcombobox.removeAllItems();
        MaNHCombobox.removeAllItems(); 
        loadKhachHang() ; 
        loadNganHang() ; 
        for(NganHang x : lNganHang){
            MaNHCombobox.addItem(x.getId() + "");
        }
        for(KhachHang x : lKhachHang){
            MaKHcombobox.addItem(x.getId() + "");
        }
    }
    
    public boolean maDaCo(int maKH, int maNH){
        for(SoTietKiem x : lSoTK){
            if(x.getKhachhang().getId() == maKH && x.getNganhang().getId() == maNH){
                return true ;
            }
        }
        return false ;
    }
    public void loadKhachHang(){
        File f = new File(fKH) ;
        if(f.exists()){
            lKhachHang = IOFile.doc(fKH) ; 
        }
        else{
            lKhachHang = new ArrayList<>() ; 
        }
    }
    
    public void loadNganHang(){
        File f = new File(fNH) ;
        if(f.exists()){
            lNganHang = IOFile.doc(fNH) ; 
        }
        else{
            lNganHang = new ArrayList<>() ; 
        }
    }
    
    public void loadSoTK(){
        File f = new File(fSo) ;
        if(f.exists()){
            lSoTK = IOFile.doc(fSo) ; 
        }
        else{
            lSoTK = new ArrayList<>() ; 
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        KHtb = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        maKH = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        hotenKH = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        diachiKH = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        loaiKH = new javax.swing.JComboBox<>();
        nhapKHbt = new javax.swing.JButton();
        SuaKHbt = new javax.swing.JButton();
        luuKHbt = new javax.swing.JButton();
        hienthiKHbt = new javax.swing.JButton();
        cappnhatKHbt = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        NganHangtb = new javax.swing.JTable();
        jPanel5 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        maNH = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        tenNH = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        laisuat = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        nhapNHbt = new javax.swing.JButton();
        XoaNHbt = new javax.swing.JButton();
        luuNHbt = new javax.swing.JButton();
        capnhatNHbt = new javax.swing.JButton();
        hienthiNHbt = new javax.swing.JButton();
        SapxepNHbt = new javax.swing.JComboBox<>();
        jPanel7 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jPanel8 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        MaKHcombobox = new javax.swing.JComboBox<>();
        MaNHCombobox = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        tiengui = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        thanggui = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        ngaygui = new javax.swing.JTextField();
        themSobt = new javax.swing.JButton();
        hienthiSobt = new javax.swing.JButton();
        luusobt = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        KHtb.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        KHtb.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                KHtbMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(KHtb);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 242, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 421, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 406, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jLabel1.setText("Ma KH");

        maKH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maKHActionPerformed(evt);
            }
        });

        jLabel2.setText("Ho va ten");

        jLabel3.setText("Dia chi");

        jLabel4.setText("Loai KH");

        loaiKH.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ca nhan ", "Tap the", "Doanh nghiep", " " }));

        nhapKHbt.setText("Nhap KH");
        nhapKHbt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nhapKHbtActionPerformed(evt);
            }
        });

        SuaKHbt.setText("Sua");
        SuaKHbt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SuaKHbtActionPerformed(evt);
            }
        });

        luuKHbt.setText("Luu vao file");
        luuKHbt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                luuKHbtActionPerformed(evt);
            }
        });

        hienthiKHbt.setText("Hien thi");
        hienthiKHbt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hienthiKHbtActionPerformed(evt);
            }
        });

        cappnhatKHbt.setText("Cap nhat");
        cappnhatKHbt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cappnhatKHbtActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 394, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(nhapKHbt)
                        .addGap(18, 18, 18)
                        .addComponent(SuaKHbt)
                        .addGap(18, 18, 18)
                        .addComponent(luuKHbt)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(hienthiKHbt)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cappnhatKHbt)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(loaiKH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 59, Short.MAX_VALUE)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(32, 32, 32)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(hotenKH, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(maKH, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(diachiKH, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(maKH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(hotenKH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(diachiKH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(loaiKH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nhapKHbt)
                            .addComponent(SuaKHbt)
                            .addComponent(luuKHbt)
                            .addComponent(hienthiKHbt)
                            .addComponent(cappnhatKHbt))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Thong tin khach hang", jPanel1);

        NganHangtb.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        NganHangtb.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                NganHangtbMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(NganHangtb);

        jLabel6.setText("Ma NH");

        jLabel7.setText("Ten ngan hang");

        jLabel8.setText("Lai suat theo nam");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(laisuat, javax.swing.GroupLayout.DEFAULT_SIZE, 107, Short.MAX_VALUE)
                    .addComponent(tenNH)
                    .addComponent(maNH))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(maNH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(tenNH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(laisuat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(179, Short.MAX_VALUE))
        );

        nhapNHbt.setText("Nhap NH");
        nhapNHbt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nhapNHbtActionPerformed(evt);
            }
        });

        XoaNHbt.setText("Xoa");
        XoaNHbt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                XoaNHbtActionPerformed(evt);
            }
        });

        luuNHbt.setText("Luu vao file");
        luuNHbt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                luuNHbtActionPerformed(evt);
            }
        });

        capnhatNHbt.setText("Cap nhat");
        capnhatNHbt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                capnhatNHbtActionPerformed(evt);
            }
        });

        hienthiNHbt.setText("Hien thi");
        hienthiNHbt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hienthiNHbtActionPerformed(evt);
            }
        });

        SapxepNHbt.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Sap xep theo--", "Ten nh", "Lai suat", " ", " " }));
        SapxepNHbt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SapxepNHbtActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(nhapNHbt)
                .addGap(18, 18, 18)
                .addComponent(XoaNHbt)
                .addGap(18, 18, 18)
                .addComponent(luuNHbt)
                .addGap(18, 18, 18)
                .addComponent(hienthiNHbt)
                .addGap(18, 18, 18)
                .addComponent(capnhatNHbt)
                .addGap(18, 18, 18)
                .addComponent(SapxepNHbt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nhapNHbt)
                    .addComponent(XoaNHbt)
                    .addComponent(luuNHbt)
                    .addComponent(capnhatNHbt)
                    .addComponent(hienthiNHbt)
                    .addComponent(SapxepNHbt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(49, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 407, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 31, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(323, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Thong tin ngan hang", jPanel2);

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(jTable3);

        jLabel10.setText("Ma KH");

        jLabel11.setText("Ma NH");

        MaKHcombobox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " " }));
        MaKHcombobox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MaKHcomboboxActionPerformed(evt);
            }
        });

        MaNHCombobox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " " }));

        jLabel12.setText("So tien gui");

        jLabel13.setText("So thang gui");

        jLabel5.setText("Ngay gui");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, 76, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(MaNHCombobox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(tiengui)
                        .addComponent(thanggui)
                        .addComponent(MaKHcombobox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(ngaygui, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(57, 57, 57))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(MaKHcombobox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(MaNHCombobox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(tiengui, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(thanggui, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(ngaygui, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(220, Short.MAX_VALUE))
        );

        themSobt.setText("Them moi");
        themSobt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                themSobtActionPerformed(evt);
            }
        });

        hienthiSobt.setText("Hien thi");
        hienthiSobt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hienthiSobtActionPerformed(evt);
            }
        });

        luusobt.setText("Luu vao file");
        luusobt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                luusobtActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(themSobt)
                        .addGap(52, 52, 52)
                        .addComponent(hienthiSobt)
                        .addGap(60, 60, 60)
                        .addComponent(luusobt))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 415, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 39, Short.MAX_VALUE)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 67, Short.MAX_VALUE)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(themSobt)
                            .addComponent(hienthiSobt)
                            .addComponent(luusobt))
                        .addGap(48, 48, 48)))
                .addContainerGap(300, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Thong tin so tiet kiem", jPanel7);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void luusobtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_luusobtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_luusobtActionPerformed

    private void hienthiSobtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hienthiSobtActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_hienthiSobtActionPerformed

    private void themSobtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_themSobtActionPerformed
        // TODO add your handling code here:
        int maS = Integer.parseInt(MaKHcombobox.getSelectedItem().toString()) ;
        int maBD = Integer.parseInt(MaNHCombobox.getSelectedItem().toString()) ;
        if(maDaCo(maS, maBD)){
            JOptionPane.showMessageDialog(this, "Trùng cả 2 mã rồi!");
            MaKHcombobox.requestFocus();
            return ;
        }

    }//GEN-LAST:event_themSobtActionPerformed

    private void MaKHcomboboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MaKHcomboboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MaKHcomboboxActionPerformed

    private void hienthiNHbtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hienthiNHbtActionPerformed
        // TODO add your handling code here:
        loadNganHang() ;
        tmNH.setRowCount(0);
        for(NganHang x : lNganHang){
            tmNH.addRow(x.toObject());
        }
    }//GEN-LAST:event_hienthiNHbtActionPerformed

    private void capnhatNHbtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_capnhatNHbtActionPerformed
        // TODO add your handling code here:
        String name;
        int ls ;
        try{
            name = tenNH.getText() ;
            ls = Integer.parseInt(laisuat.getText()) ;
            NganHang s = new NganHang(name, ls) ;
            tmNH.addRow(s.toObject());
            lNganHang.add(s) ;
            nhapNHbt.setEnabled(true);
            capnhatNHbt.setEnabled(false);
        }
        catch(TrongException e){
            JOptionPane.showMessageDialog(this, "Phải điền đầy đủ các thông tin!");
            tenNH.requestFocus();
        }
        catch(NumberFormatException e){
            JOptionPane.showMessageDialog(this, "Lai suat phai dien so!");
            laisuat.requestFocus();            
        }
    }//GEN-LAST:event_capnhatNHbtActionPerformed

    private void luuNHbtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_luuNHbtActionPerformed
        // TODO add your handling code here:
        IOFile.ghi(fNH, lNganHang);
    }//GEN-LAST:event_luuNHbtActionPerformed

    private void XoaNHbtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_XoaNHbtActionPerformed
        // TODO add your handling code here:
        int n = NganHangtb.getSelectedRow() ;
        if(n >= 0 && n < NganHangtb.getRowCount()){
            tmNH.removeRow(n);
            lNganHang.remove(n) ;
        }
        else{
            JOptionPane.showMessageDialog(this, "Chon hang de xoa!");
        }
    }//GEN-LAST:event_XoaNHbtActionPerformed

    private void nhapNHbtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nhapNHbtActionPerformed
        // TODO add your handling code here:
        int n = lNganHang.size() ;
        nhapNHbt.setEnabled(false);
        capnhatNHbt.setEnabled(true);
        if(n > 0){
            NganHang.setId_n(lNganHang.get(n - 1).getId() + 1);
        }
        maNH.setText(NganHang.getId_n() + "");
        tenNH.requestFocus();
        them = true ;
    }//GEN-LAST:event_nhapNHbtActionPerformed

    private void NganHangtbMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NganHangtbMouseClicked
        // TODO add your handling code here:
        int n = NganHangtb.getSelectedRow() ;
        if(n >= 0 && n < NganHangtb.getRowCount()){
            maNH.setText(tmNH.getValueAt(n, 0).toString());
            tenNH.setText(tmNH.getValueAt(n, 1).toString());
            laisuat.setText(tmNH.getValueAt(n, 2).toString());
        }
    }//GEN-LAST:event_NganHangtbMouseClicked

    private void cappnhatKHbtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cappnhatKHbtActionPerformed
        // TODO add your handling code here:
        if(them){
            String name, address, type;
            try{
                name = hotenKH.getText() ;
                address = diachiKH.getText() ;
                type = loaiKH.getSelectedItem().toString() ;
                KhachHang s = new KhachHang(name, address, type) ;
                tmKH.addRow(s.toObject());
                lKhachHang.add(s) ;
                nhapKHbt.setEnabled(true);
                cappnhatKHbt.setEnabled(false);
                them = false ;
            }
            catch(TrongException e){
                JOptionPane.showMessageDialog(this, "Phải điền đầy đủ các thông tin!");
                hotenKH.requestFocus();
            }
        }
        if(sua){
            int row = KHtb.getSelectedRow()  ;
            String name, address, type;
            int id ;
            try{
                id = Integer.valueOf(maKH.getText()) ;
                name = hotenKH.getText() ;
                address = diachiKH.getText() ;
                type = loaiKH.getSelectedItem().toString() ;
                KhachHang s = new KhachHang(name, address, type) ;
                lKhachHang.set(row - 1, s) ;
                tmKH.setValueAt(id, row, 0);
                tmKH.setValueAt(name, row, 1);
                tmKH.setValueAt(address, row, 2);
                tmKH.setValueAt(type, row, 3);
                SuaKHbt.setEnabled(true);
                cappnhatKHbt.setEnabled(false);
                sua = false ;
            }
            catch(TrongException e){
                JOptionPane.showMessageDialog(this, "Phải điền đầy đủ các thông tin!");
                hotenKH.requestFocus();
            }
        }
    }//GEN-LAST:event_cappnhatKHbtActionPerformed

    private void hienthiKHbtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hienthiKHbtActionPerformed
        // TODO add your handling code here:
        loadKhachHang() ;
        tmKH.setRowCount(0);
        for(KhachHang x : lKhachHang){
            tmKH.addRow(x.toObject());
        }
    }//GEN-LAST:event_hienthiKHbtActionPerformed

    private void luuKHbtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_luuKHbtActionPerformed
        // TODO add your handling code here:
        IOFile.ghi(fKH, lKhachHang);
    }//GEN-LAST:event_luuKHbtActionPerformed

    private void SuaKHbtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SuaKHbtActionPerformed
        // TODO add your handling code here:
        int row = KHtb.getSelectedRow() ;
        if(row < 0 || row > KHtb.getRowCount()){
            JOptionPane.showMessageDialog(this, "Chon cot ma sua!");
            hotenKH.requestFocus();
            return ;
        }
        SuaKHbt.setEnabled(false);
        cappnhatKHbt.setEnabled(true);
        sua = true ;
    }//GEN-LAST:event_SuaKHbtActionPerformed

    private void nhapKHbtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nhapKHbtActionPerformed
        // TODO add your handling code here:
        int n = lKhachHang.size() ;
        nhapKHbt.setEnabled(false);
        cappnhatKHbt.setEnabled(true);
        
        if(n > 0){
            KhachHang.setId_n(lKhachHang.get(n - 1).getId() + 1);
        }
        maKH.setText(KhachHang.getId_n() + "");
        hotenKH.requestFocus();
        them = true ;
        
    }//GEN-LAST:event_nhapKHbtActionPerformed

    private void maKHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maKHActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_maKHActionPerformed

    private void KHtbMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_KHtbMouseClicked
        // TODO add your handling code here:
        int n = KHtb.getSelectedRow() ;
        if(n >= 0 && n < KHtb.getRowCount()){
            maKH.setText(tmKH.getValueAt(n, 0).toString());
            hotenKH.setText(tmKH.getValueAt(n, 1).toString());
            diachiKH.setText(tmKH.getValueAt(n, 2).toString());
            loaiKH.setSelectedItem(tmKH.getValueAt(n, 3));
        }
    }//GEN-LAST:event_KHtbMouseClicked

    private void SapxepNHbtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SapxepNHbtActionPerformed
        // TODO add your handling code here:
        if(SapxepNHbt.getSelectedIndex() == 1){
            lNganHang.sort(new Comparator<NganHang>(){
                @Override
                public int compare(NganHang o1, NganHang o2) {
                    String[] t1 = o1.getName().split("\\s+") ;
                    String[] t2 = o2.getName().split("\\s+") ;
                    String n1 = t1[t1.length - 1] + o1.getName() ;
                    String n2 = t2[t2.length - 1] + o2.getName() ;
                    return n1.compareTo(n2) ;
                } 
                
            });
        }
        if(SapxepNHbt.getSelectedIndex() == 2){
            lNganHang.sort(new Comparator<NganHang>(){
                @Override
                public int compare(NganHang o1, NganHang o2) {
                    return o1.getAmount() - o2.getAmount() ;
                } 
                
            });
        }
        tmNH.setRowCount(0);
        for(NganHang x : lNganHang){
            tmNH.addRow(x.toObject());
        }
    }//GEN-LAST:event_SapxepNHbtActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable KHtb;
    private javax.swing.JComboBox<String> MaKHcombobox;
    private javax.swing.JComboBox<String> MaNHCombobox;
    private javax.swing.JTable NganHangtb;
    private javax.swing.JComboBox<String> SapxepNHbt;
    private javax.swing.JButton SuaKHbt;
    private javax.swing.JButton XoaNHbt;
    private javax.swing.JButton capnhatNHbt;
    private javax.swing.JButton cappnhatKHbt;
    private javax.swing.JTextField diachiKH;
    private javax.swing.JButton hienthiKHbt;
    private javax.swing.JButton hienthiNHbt;
    private javax.swing.JButton hienthiSobt;
    private javax.swing.JTextField hotenKH;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable3;
    private javax.swing.JTextField laisuat;
    private javax.swing.JComboBox<String> loaiKH;
    private javax.swing.JButton luuKHbt;
    private javax.swing.JButton luuNHbt;
    private javax.swing.JButton luusobt;
    private javax.swing.JTextField maKH;
    private javax.swing.JTextField maNH;
    private javax.swing.JTextField ngaygui;
    private javax.swing.JButton nhapKHbt;
    private javax.swing.JButton nhapNHbt;
    private javax.swing.JTextField tenNH;
    private javax.swing.JTextField thanggui;
    private javax.swing.JButton themSobt;
    private javax.swing.JTextField tiengui;
    // End of variables declaration//GEN-END:variables
}
